import ChakraProviders from "./providers/ChakraProvider";
import { Inter } from "next/font/google";
import HeaderLayout from "./components/Layouts/HeaderLayout";
// import i18n from "./core/i18n";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProviders>
          <HeaderLayout>{children}</HeaderLayout>
        </ChakraProviders>
      </body>
    </html>
  );
}
