import ChakraProviders from "../providers/ChakraProvider";
import HeaderLayout from "../components/Layouts/HeaderLayout";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { iranSans, josefSans, lato } from "@/utils/fonts";
import "../globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { locale } }) {
  let messages;
  try {
    messages = (await import(`../../../messages/${locale}.json`)).default;
  } catch (error) {
    // notFound();
  }
  return (
    <html lang={locale} dir={locale === "en" ? "ltr" : "rtl"}>
      <body className={locale === "en" ? lato.className : iranSans.className}>
        <ChakraProviders>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <HeaderLayout>{children}</HeaderLayout>
          </NextIntlClientProvider>
        </ChakraProviders>
      </body>
    </html>
  );
}
